import Foundation
import SwiftData

/// ユーザーの音声教材から抽出した単語(英語フレーズ+和訳)を一度だけ投入する
enum VocabSeedData {
    /// (英語, 和訳)。音声の収録順。
    static let entries: [(String, String)] = [
        ("Alter the pattern of behavior.", "行動パターンを変える"),
        ("Problems arise from carelessness.", "問題は不注意から生じる"),
        ("Transform food into energy.", "食べ物をエネルギーに変える"),
        ("Defeat the champion.", "チャンピオンを打ち負かす"),
        ("Investigate the cause of the failure.", "失敗の原因を調査する"),
        ("Bury a treasure.", "宝物を埋める"),
        ("Cope with problems.", "問題にうまく対処する"),
        ("This problem often occurs.", "この問題はしばしば起こる"),
        ("Accomplish the difficult task.", "困難な仕事を成し遂げる"),
        ("Don't hesitate to ask questions.", "遠慮せずに質問しなさい"),
        ("Endure great pain.", "大きな苦痛に耐える"),
        ("Conclude that he is OK.", "彼は大丈夫だと結論づける"),
        ("Guarantee your success.", "君の成功を保証する"),
        ("Dominate the world economy.", "世界経済を支配する"),
        ("Confirm Darwin's theory.", "ダーウィンの理論を裏づける"),
        ("Greet people with a smile.", "笑顔で人にあいさつする"),
        ("Entertain the audience.", "観客を楽しませる"),
        ("Defend ourselves against attack.", "攻撃から身を守る"),
        ("Forbid him to go out.", "彼の外出を禁じる"),
        ("Broadcast the concert live.", "コンサートを生放送する"),
        ("Sacrifice everything for love.", "愛のためにすべてを犠牲にする"),
        ("Punish him for the crime.", "その罪で彼を罰する"),
        ("Glance at the clock.", "時計をちらりと見る"),
        ("Retain the world title.", "世界タイトルを保持する"),
        ("Calculate the cost.", "費用を計算する"),
        ("Flee a sinking ship.", "沈む船から逃げる"),
        ("Rescue a man from a fire.", "火事から人を救助する"),
        ("Beg him to come back.", "戻ってきてと彼に懇願する"),
        ("Define a day as 24 hours.", "1日を24時間と定義する"),
        ("It is easy to deceive people.", "人をだますのは簡単だ"),
        ("Convey information.", "情報を伝える"),
        ("Energy to sustain life.", "生命を維持するためのエネルギー"),
        ("Purchase the land.", "その土地を購入する"),
        ("Memories of the war fade away.", "戦争の記憶が薄れていく"),
        ("Regulate traffic.", "交通を規制する"),
        ("Distribute food equally.", "食料を平等に分配する"),
        ("Enhance the quality of life.", "生活の質を高める"),
        ("Chat with friends.", "友達とおしゃべりする"),
        ("Demand exceeds supply.", "需要が供給を上回る"),
        ("Wipe the table.", "テーブルを拭く"),
        ("Cooperate with each other.", "互いに協力する"),
        ("Inherit genes from our parents.", "親から遺伝子を受け継ぐ"),
        ("Unite the Arab world.", "アラブ世界を統一する"),
        ("Look before you leap.", "跳ぶ前に見よ(転ばぬ先の杖)"),
        ("Exaggerate the size of the fish.", "魚の大きさを誇張する"),
        ("Conquer the world.", "世界を征服する"),
        ("The snow will melt soon.", "雪はすぐに溶けるだろう"),
        ("Invade Poland.", "ポーランドに侵攻する"),
        ("Modify the plan.", "計画を修正する"),
        ("Scatter toys on the floor.", "床におもちゃをまき散らす"),
        ("Undergo great changes.", "大きな変化を経験する"),
        ("Evaluate online information.", "ネット上の情報を評価する"),
        ("Bend down to pick up the can.", "缶を拾おうと身をかがめる"),
        ("The word derives from Latin.", "その単語はラテン語に由来する"),
        ("A girl screaming for help.", "助けを求めて叫ぶ少女"),
        ("Gaze at the stars.", "星をじっと見つめる"),
        ("Pray for a sick child.", "病気の子どものために祈る"),
        ("Polish the shoes.", "靴を磨く"),
        ("Classify man as an animal.", "人間を動物に分類する"),
        ("Assert that it is impossible.", "それは不可能だと主張する"),
        ("Grab him by the arm.", "彼の腕をつかむ"),
        ("Fold a piece of paper.", "紙を折りたたむ"),
        ("Sweep the floor.", "床を掃く"),
        ("Whisper in her ear.", "彼女の耳もとでささやく"),
        ("Imitate human behavior.", "人間の行動をまねる"),
        ("Stop and stare at her.", "立ち止まって彼女をじっと見る"),
        ("Emphasize the importance of health.", "健康の大切さを強調する"),
        ("Get rid of stress.", "ストレスを取り除く"),
        ("Pour wine into the glass.", "グラスにワインを注ぐ"),
        ("Vanish from sight.", "視界から消える"),
        ("Restore the old building.", "古い建物を修復する"),
        ("Deserve to be punished.", "罰を受けて当然である"),
        ("A space science laboratory.", "宇宙科学の研究所"),
        ("An international conference.", "国際会議"),
        ("Cross the American continent.", "アメリカ大陸を横断する"),
        ("National health insurance.", "国民健康保険"),
        ("The crew of the Space Shuttle.", "スペースシャトルの乗組員"),
        ("Live in poverty.", "貧困の中で暮らす"),
        ("Water shortage.", "水不足"),
        ("International affairs.", "国際情勢"),
        ("The only exception to the rule.", "その規則の唯一の例外"),
        ("Work for low wages.", "低賃金で働く"),
        ("Knowledge and wisdom.", "知識と知恵"),
        ("Pay taxes on the land.", "土地に税金を払う"),
        ("Human evolution.", "人類の進化"),
        ("The language barrier.", "言葉の壁"),
        ("Fall into the same category.", "同じ部類に入る"),
        ("The family as a social unit.", "社会の単位としての家族"),
        ("The restaurant's reputation.", "そのレストランの評判"),
        ("The virtue of hard work.", "勤勉という美徳"),
        ("Have the courage to tell the truth.", "真実を語る勇気を持つ"),
        ("Feel sympathy for the victim.", "被害者に同情する"),
        ("A labor union.", "労働組合"),
        ("Western civilization.", "西洋文明"),
        ("A 10,000-volume library.", "蔵書1万冊の図書館"),
        ("Cherry blossoms.", "桜の花"),
        ("The beginning of a new era.", "新しい時代の始まり"),
        ("Settle international disputes.", "国際紛争を解決する"),
        ("The tourism industry in Japan.", "日本の観光産業"),
        ("The history of mankind.", "人類の歴史"),
        ("Mass murder.", "大量殺人"),
        ("Landscape painting.", "風景画"),
        ("Reach the final destination.", "最終目的地に着く"),
        ("Tell a fairy tale.", "おとぎ話をする"),
        ("Political reform.", "政治改革"),
        ("Muscles and bones.", "筋肉と骨"),
        ("Future prospects.", "将来の見通し"),
        ("Run a large corporation.", "大企業を経営する"),
        ("A former British colony.", "かつてのイギリスの植民地"),
        ("A quarrel with my wife.", "妻との口げんか"),
        ("An intellectual profession.", "知的な職業"),
        ("Unique aspects of Japanese culture.", "日本文化の独特な側面"),
        ("A three-minute pause.", "3分間の中断"),
        ("The conflict between the two sides.", "両者の対立"),
        ("White privilege.", "白人の特権"),
        ("Economic prosperity.", "経済的繁栄"),
        ("A musical genius.", "音楽の天才"),
        ("Symptoms of a cold.", "風邪の症状"),
        ("His greatest merit.", "彼の最大の長所"),
        ("Destroy the ozone layer.", "オゾン層を破壊する"),
        ("A clue to the mystery.", "謎を解く手がかり"),
        ("Under any circumstances.", "どんな状況でも"),
        ("The city's business district.", "その都市の商業地区"),
        ("Spend two years in prison.", "刑務所で2年間過ごす"),
        ("My traveling companion.", "私の旅の連れ"),
        ("Chief executive officer.", "最高経営責任者"),
        ("A strong sense of justice.", "強い正義感"),
        ("The check-in procedure.", "チェックインの手続き"),
        ("The sun's rays.", "太陽の光線"),
        ("Go to heaven.", "天国へ行く"),
        ("Lead a life of luxury.", "ぜいたくな生活を送る"),
        ("Oxygen in the air.", "空気中の酸素"),
        ("Lack of funds.", "資金不足"),
        ("The theme of the book.", "その本のテーマ"),
        ("The boundary between two countries.", "2国間の境界"),
        ("His ambition to be a writer.", "作家になるという彼の野望"),
        ("The weather forecast.", "天気予報"),
        ("Study social psychology.", "社会心理学を学ぶ"),
        ("Do hard labor.", "重労働をする"),
        ("The International Olympic Committee.", "国際オリンピック委員会"),
        ("A physician at the hospital.", "その病院の内科医"),
        ("His philosophy of life.", "彼の人生哲学"),
        ("A deep affection for animals.", "動物への深い愛情"),
        ("A candidate for president.", "大統領候補"),
        ("An atomic bomb.", "原子爆弾"),
        ("Give top priority to safety.", "安全を最優先する"),
        ("An obstacle to communication.", "コミュニケーションの障害"),
        ("Have no appetite.", "食欲がない"),
        ("Relieve tension.", "緊張を和らげる"),
        ("A Native American tribe.", "アメリカ先住民の部族"),
        ("Cut the defense budget.", "国防予算を削減する"),
        ("The campaign to promote tourism.", "観光を促進する運動"),
        ("Joy and sorrow.", "喜びと悲しみ"),
        ("A communication satellite.", "通信衛星"),
        ("A deep insight into life.", "人生への深い洞察"),
        ("Have a bad cough.", "ひどい咳が出る"),
        ("Decide the fate of the world.", "世界の運命を決める"),
        ("A training scheme for pilots.", "パイロットの訓練計画"),
        ("The inhabitants of the country.", "その国の住民"),
        ("Burn fossil fuels.", "化石燃料を燃やす"),
        ("The motive for the crime.", "犯罪の動機"),
        ("Human instinct to fight.", "人間の闘争本能"),
        ("The legend of Robin Hood.", "ロビン・フッドの伝説"),
        ("The Roman Empire.", "ローマ帝国"),
        ("Study modern architecture.", "現代建築を学ぶ"),
        ("Love and passion.", "愛と情熱"),
        ("The treatment of cancer.", "がんの治療"),
        ("Persuade him with logic.", "論理で彼を説得する"),
        ("Two dozen eggs.", "2ダースの卵"),
        ("A good harvest of rice.", "米の豊作"),
        ("Test the hypothesis.", "仮説を検証する"),
        ("The first voyage of Columbus.", "コロンブスの最初の航海"),
        ("The editor of a fashion magazine.", "ファッション誌の編集者"),
        ("The Southern Hemisphere.", "南半球"),
        ("The mechanism of a clock.", "時計の仕組み"),
        ("Anthropologists study people.", "人類学者は人間を研究する"),
        ("Greek tragedy.", "ギリシャ悲劇"),
        ("Resistance to antibiotics.", "抗生物質への耐性"),
        ("Pay the bus fare.", "バスの運賃を払う"),
        ("Pay the debt.", "借金を返す"),
        ("The high school curriculum.", "高校の教育課程"),
        ("The components of the body.", "身体の構成要素"),
        ("Modern English usage.", "現代英語の語法"),
        ("A sand castle.", "砂の城"),
        ("A terrible famine in Africa.", "アフリカのひどい飢饉"),
        ("English folk music.", "イギリスの民族音楽"),
        ("The population explosion.", "人口爆発"),
        ("A large portion of your salary.", "給料の大部分"),
        ("Marine organisms.", "海洋生物"),
        ("The Merchant of Venice.", "ベニスの商人"),
        ("Ancient Greek myths.", "古代ギリシャ神話"),
        ("Protect wildlife.", "野生生物を保護する"),
        ("The United States Congress.", "アメリカ合衆国議会"),
        ("Chinese children work harder than their Japanese counterparts.", "中国の子どもは日本の子どもよりよく勉強する"),
        ("Tackle environmental problems.", "環境問題に取り組む"),
        ("Scold my son for being lazy.", "怠けている息子を叱る"),
        ("Install solar panels on the roof.", "屋根にソーラーパネルを設置する"),
        ("Extract DNA from blood.", "血液からDNAを抽出する"),
        ("Bump into someone.", "人にばったり出会う"),
        ("Don't despise poor people.", "貧しい人を軽蔑するな"),
        ("Tolerate pain.", "痛みに耐える"),
        ("Boast of being rich.", "金持ちであることを自慢する"),
        ("The European economy is flourishing.", "ヨーロッパ経済は繁栄している"),
        ("Disregard safety rules.", "安全規則を無視する"),
        ("Don't tease me.", "私をからかわないで"),
        ("Reinforce the belief.", "その信念を強める"),
        ("Strive to survive.", "生き残ろうと努力する"),
        ("Coordinate movements with each other.", "互いに動きを調整する"),
        ("Yawn when you are bored.", "退屈するとあくびをする"),
        ("Hug and kiss him.", "彼を抱きしめてキスする"),
        ("Combat global warming.", "地球温暖化と闘う"),
        ("Knit a sweater.", "セーターを編む"),
        ("Mental fatigue.", "精神的疲労"),
        ("Win fame and fortune.", "名声と富を手に入れる"),
        ("The room is a mess.", "部屋が散らかっている"),
        ("At intervals of 10 minutes.", "10分間隔で"),
        ("Help him with his luggage.", "彼の荷物を運ぶのを手伝う"),
        ("On behalf of the class.", "クラスを代表して"),
        ("Feel an impulse to shout.", "叫びたい衝動にかられる"),
        ("Debris from an explosion.", "爆発の破片"),
        ("Beauty and the Beast.", "美女と野獣"),
        ("Believe a foolish superstition.", "ばかげた迷信を信じる"),
        ("The illusion that Japan is safe.", "日本は安全だという幻想"),
        ("Cotton thread.", "木綿の糸"),
        ("Reduce salt intake.", "塩分の摂取量を減らす"),
        ("Invite guests to the feast.", "祝宴に客を招く"),
        ("A seasonal transition.", "季節の変わり目"),
        ("The misery of war.", "戦争の悲惨さ"),
        ("Dangerous radiation.", "危険な放射線"),
        ("A log cabin.", "丸太小屋"),
        ("Reach consensus on the issue.", "その問題で合意に達する"),
        ("Do a good deed a day.", "1日1善を行う"),
        ("An old Chinese proverb.", "中国の古いことわざ"),
        ("Thank you for the compliment.", "お褒めの言葉をありがとう"),
        ("Watch the candle flame.", "ろうそくの炎を見つめる"),
        ("Celebrate their wedding anniversary.", "結婚記念日を祝う"),
        ("Follow your conscience.", "良心に従う"),
        ("An expedition to the moon.", "月への探検"),
        ("Produce offspring.", "子孫を残す"),
        ("My monthly allowance.", "私の毎月のこづかい"),
        ("A newspaper headline.", "新聞の見出し"),
        ("Sign a peace treaty.", "平和条約に調印する"),
        ("A historical monument.", "歴史的な記念碑"),
        ("A worm in the apple.", "リンゴの中の虫"),
        ("A good remedy for colds.", "風邪によく効く治療法"),
        ("A 20-volume encyclopedia.", "全20巻の百科事典"),
        ("Catch a glimpse of her face.", "彼女の顔がちらりと見える"),
        ("School personnel.", "学校の職員"),
        ("The triumph of science.", "科学の勝利"),
        ("Reading, writing and arithmetic.", "読み書きと算数"),
        ("People with low self-esteem.", "自尊心の低い人々"),
        ("Microbes in the soil.", "土壌の中の微生物"),
        ("The odds of successful treatment.", "治療が成功する見込み"),
        ("A society in chaos.", "混乱状態の社会"),
        ("Control the destiny of mankind.", "人類の運命を左右する"),
        ("A disc five inches in diameter.", "直径5インチの円盤"),
        ("Win the lottery.", "宝くじに当たる"),
        ("A souvenir shop in Hong Kong.", "香港のみやげ物店"),
        ("Walk along a mountain trail.", "山道を歩く"),
        ("A ratio of 10 to 1.", "10対1の比率"),
        ("Fight with a sword.", "剣で戦う"),
        ("Blow a whistle.", "笛を吹く"),
        ("Public sentiment against slavery.", "奴隷制に反対する世論感情"),
        ("Share household chores.", "家事を分担する"),
        ("Be treated with courtesy.", "礼儀正しく扱われる"),
        ("The New York City mayor.", "ニューヨーク市長"),
        ("Video surveillance systems.", "ビデオ監視システム"),
        ("A big black trash bag.", "大きな黒いゴミ袋"),
        ("Gain wealth and prestige.", "富と名声を手に入れる"),
        ("Police headquarters.", "警察本部"),
        ("Explore the vast wilderness.", "広大な荒野を探検する"),
        ("The earth's orbit around the sun.", "太陽を回る地球の軌道"),
        ("Have a personal bias against women.", "女性への個人的偏見を持つ"),
        ("The Republic of Ireland.", "アイルランド共和国"),
        ("This house is a bargain.", "この家は掘り出し物だ"),
        ("In the domain of psychology.", "心理学の領域で"),
        ("A fragment of blue glass.", "青いガラスの破片"),
        ("The Andromeda galaxy.", "アンドロメダ銀河"),
        ("Sit on mother's lap.", "母のひざの上に座る"),
        ("The deadline for the report.", "レポートの締め切り"),
        ("Faster than a bullet.", "弾丸よりも速い"),
        ("The safety of pedestrians.", "歩行者の安全"),
        ("A conversation full of wit.", "機知に富んだ会話"),
        ("A nuisance to others.", "他人への迷惑"),
        ("Meet the criteria for safety.", "安全基準を満たす"),
        ("Face economic hardship.", "経済的苦難に直面する"),
        ("The glory of the British Empire.", "大英帝国の栄光"),
        ("Walk along the pavement.", "歩道を歩く"),
        ("The British navy.", "イギリス海軍"),
        ("A movie script.", "映画の台本"),
        ("The old-age pension.", "老齢年金"),
        ("The province of Quebec.", "ケベック州"),
        ("A surplus of food.", "食料の余剰"),
        ("Add moisture to the skin.", "肌に水分を与える"),
        ("A leather elbow patch.", "革のひじ当て"),
        ("At an altitude of 30,000 feet.", "高度3万フィートで"),
        ("The thermometer shows zero degrees Celsius.", "温度計は摂氏0度を示している"),
        ("Pay college tuition.", "大学の授業料を払う"),
        ("Send Japanese troops abroad.", "日本の軍隊を海外に送る"),
        ("Humans and other primates.", "人間とその他の霊長類"),
        ("Find flaws in his argument.", "彼の主張の欠陥を見つける"),
        ("His son and nephew.", "彼の息子とおい"),
        ("Wear a silk garment.", "絹の衣服を着る"),
        ("The diagnosis of disease.", "病気の診断"),
        ("Industry and commerce.", "産業と商業"),
        ("The art of antiquity.", "古代の芸術"),
        ("A small fraction of the money.", "その金のごく一部"),
        ("The irony of fate.", "運命の皮肉"),
        ("Have a nightmare.", "悪夢を見る"),
        ("A defect in the structure.", "構造上の欠陥"),
        ("A birth certificate.", "出生証明書"),
        ("Prevent the decay of food.", "食べ物の腐敗を防ぐ"),
        ("Prevent soil erosion.", "土壌の浸食を防ぐ"),
        ("A recipe for happiness.", "幸福の秘訣"),
        ("The human skeleton.", "人間の骨格"),
        ("The grace of her movements.", "彼女の動きの優雅さ"),
        ("Visit some Paris landmarks.", "パリの名所を訪れる"),
        ("The symptoms of dementia.", "認知症の症状"),
        ("Flesh and blood.", "肉と血(生身の人間)"),
        ("Collision with the earth.", "地球への衝突"),
        ("A hazard to health.", "健康への危険"),
        ("The tomb of the unknown soldier.", "無名戦士の墓"),
        ("Take daily injections.", "毎日注射を打つ"),
        ("A breakthrough in technology.", "技術の飛躍的進歩"),
        ("A leather bag.", "革のかばん"),
        ("A jewelry store.", "宝石店"),
        ("Read nonverbal cues.", "言葉によらない合図を読み取る"),
        ("Call an ambulance right away.", "すぐに救急車を呼ぶ"),
        ("A real estate agent.", "不動産業者"),
        ("An export commodity.", "輸出商品"),
        ("Check the departure time.", "出発時刻を確認する"),
        ("Enter a new phase.", "新しい段階に入る"),
        ("A car thief.", "自動車泥棒"),
        ("St. Valentine.", "聖バレンタイン"),
        ("Painting and sculpture.", "絵画と彫刻"),
        ("Feel deep grief over his death.", "彼の死に深い悲しみを覚える"),
        ("Drive in the fast lane.", "追い越し車線を走る"),
        ("Predators like lions.", "ライオンのような捕食動物"),
        ("Fluids like water and air.", "水や空気のような流体"),
        ("An incentive to work.", "働く動機づけ"),
        ("The bride and her father.", "花嫁とその父親"),
        ("Military intervention in Iraq.", "イラクへの軍事介入"),
        ("Win by a wide margin.", "大差で勝つ"),
        ("A biography of Einstein.", "アインシュタインの伝記"),
        ("Marry without parental consent.", "親の同意なしに結婚する"),
        ("A smoking volcano.", "煙を上げる火山"),
        ("Anti-government rebels.", "反政府の反乱者たち"),
        ("The metaphor of the melting pot.", "人種のるつぼという比喩"),
        ("Gun control legislation.", "銃規制の法律"),
        ("Be struck by lightning.", "雷に打たれる"),
        ("The use of pesticides.", "農薬の使用"),
        ("Write a newspaper column.", "新聞のコラムを書く"),
        ("Spread a rumor about a ghost.", "幽霊のうわさを広める"),
        ("Tiny dust particles.", "微細なほこりの粒子"),
        ("A dialogue between two students.", "2人の学生の対話"),
        ("Learn English in kindergarten.", "幼稚園で英語を学ぶ"),
        ("A patient with type 2 diabetes.", "2型糖尿病の患者"),
        ("Buckingham Palace.", "バッキンガム宮殿"),
        ("Do the laundry.", "洗濯をする"),
        ("Patients in the ward.", "病棟の患者たち"),
        ("Rely on your spouse.", "配偶者に頼る"),
        ("A cholera epidemic.", "コレラの流行"),
        ("America's infant mortality rate.", "アメリカの乳児死亡率"),
        ("Economy class syndrome.", "エコノミークラス症候群"),
        ("The retail price.", "小売価格"),
        ("Take a large dose of vitamin C.", "ビタミンCを大量に摂取する"),
        ("Alcoholic beverages.", "アルコール飲料"),
        ("Regulate metabolism.", "新陳代謝を調節する"),
        ("A hybrid of two plants.", "2つの植物の雑種"),
        ("The sweet scent of roses.", "バラの甘い香り"),
        ("Reduce inflammation in the eye.", "目の炎症を抑える"),
        ("Take sleeping pills.", "睡眠薬を飲む"),
        ("Be in grave danger.", "重大な危険にさらされている"),
        ("Fertile soil.", "肥沃な土壌"),
        ("Be hostile to the government.", "政府に敵意を持っている"),
        ("Water is indispensable to life.", "水は生命に不可欠だ"),
        ("An information-oriented society.", "情報化社会"),
        ("A splendid view.", "すばらしい眺め"),
        ("A competent teacher.", "有能な教師"),
        ("Supreme joy.", "最高の喜び"),
        ("Straightforward language.", "率直な言葉"),
        ("A land sacred to Islam.", "イスラム教の聖地"),
        ("Take bold action.", "大胆な行動をとる"),
        ("Feel uneasy about the future.", "将来に不安を感じる"),
        ("Neat clothes.", "きちんとした服装"),
        ("A shallow river.", "浅い川"),
        ("Make a fake cake.", "偽物のケーキを作る"),
        ("A superficial difference.", "表面的な違い"),
        ("A completely absurd idea.", "まったくばかげた考え"),
        ("Fragile items.", "壊れやすい品物"),
        ("A girl from a respectable family.", "きちんとした家庭の娘"),
        ("Be respectful to elders.", "年長者に敬意を払う"),
        ("Schools in the respective areas.", "それぞれの地域の学校"),
        ("A magnificent view.", "壮大な眺め"),
        ("An infinite number of stars.", "無数の星"),
        ("A comprehensive study.", "包括的な研究"),
        ("A steep slope.", "急な坂"),
        ("The gross domestic product.", "国内総生産"),
        ("Prepare for subsequent events.", "その後の出来事に備える"),
        ("My sincere apologies.", "心からのおわび"),
        ("A toxic gas.", "有毒ガス"),
        ("Take a neutral position.", "中立の立場をとる"),
        ("A diligent student.", "勤勉な学生"),
        ("Have a sore throat.", "のどが痛い"),
        ("Drink contaminated water.", "汚染された水を飲む"),
        ("An oral examination.", "口頭試験"),
        ("Spend a restless night.", "眠れない夜を過ごす"),
        ("Smell like rotten eggs.", "腐った卵のようなにおいがする"),
        ("Vigorous activity.", "活発な活動"),
        ("An immense amount of information.", "膨大な量の情報"),
        ("Metropolitan areas.", "大都市圏"),
        ("Be punctual for an appointment.", "約束の時間を守る"),
        ("A solitary old man.", "孤独な老人"),
        ("Take collective action.", "集団行動をとる"),
        ("Break off diplomatic relations.", "外交関係を断つ"),
        ("A nasty smell.", "いやなにおい"),
        ("A helpless baby.", "無力な赤ん坊"),
        ("Give explicit instructions.", "明確な指示を与える"),
        ("His company went bankrupt.", "彼の会社は倒産した"),
        ("The hope of eternal life.", "永遠の命への望み"),
        ("The sole survivor.", "唯一の生存者"),
        ("Sour grapes.", "すっぱいブドウ(負け惜しみ)"),
        ("A notable exception.", "注目すべき例外"),
        ("An affluent society.", "豊かな社会"),
        ("A naked man.", "裸の男"),
        ("The vocal organ.", "発声器官"),
        ("Feminine beauty.", "女性的な美しさ"),
        ("Sit down in a vacant seat.", "空いている席に座る"),
        ("Rigid rules.", "厳格な規則"),
        ("Humid summer weather.", "蒸し暑い夏の天気"),
        ("An outstanding scholar.", "傑出した学者"),
        ("Be addicted to drugs.", "薬物中毒になっている"),
        ("Be vulnerable to attack.", "攻撃を受けやすい"),
        ("Spontaneous laughter.", "自然に出る笑い"),
        ("Be greedy for money.", "金に貪欲である"),
        ("A trivial matter.", "ささいな問題"),
        ("The risks inherent in the sport.", "そのスポーツに内在する危険"),
        ("A promising new actress.", "前途有望な新人女優"),
        ("Physiological reactions.", "生理的反応"),
        ("Clinical trials of new drugs.", "新薬の臨床試験"),
        ("Chronic disease.", "慢性疾患"),
        ("Divisions of geological time.", "地質時代の区分"),
        ("Countless species of insects.", "無数の昆虫の種"),
        ("An innate ability to learn.", "生まれつきの学習能力"),
        ("Be alert to every sound.", "あらゆる物音に警戒する"),
        ("Autonomous cars.", "自動運転車"),
        ("Occur simultaneously.", "同時に起こる"),
        ("Utterly different from others.", "他とまったく異なる"),
        ("Change drastically.", "大幅に変化する"),
        ("Not necessarily true.", "必ずしも本当ではない"),
        ("He always tells the truth, thereby avoiding troubles.", "彼は常に真実を語り、それによってトラブルを避けている"),
        ("Speak frankly.", "率直に話す"),
        ("The two cities, namely Paris and Tokyo.", "2つの都市、すなわちパリと東京"),
        ("He tried hard, hence his success.", "彼は懸命に努力した、それゆえの成功だ"),
        ("Pay bills via the internet.", "インターネット経由で請求書を支払う"),
        ("Owing to lack of fuel.", "燃料不足のために"),
        ("Clarify the meaning of the word.", "その単語の意味を明確にする"),
        ("Smash a bottle.", "瓶を粉々に割る"),
        ("Mourn Gandhi's death.", "ガンジーの死を悼む"),
        ("Summon the police.", "警察を呼び出す"),
        ("Shatter windows.", "窓を粉砕する"),
        ("Linger in my memory.", "記憶にいつまでも残る"),
        ("Lament the shortness of life.", "人生の短さを嘆く"),
        ("Be endowed with a talent.", "才能に恵まれている"),
        ("Rejoice in the success.", "成功を喜ぶ"),
        ("Allocate resources.", "資源を割り当てる"),
        ("Slap his face.", "彼の顔を平手打ちする"),
        ("Contend that money cannot buy happiness.", "金で幸福は買えないと主張する"),
        ("Swear never to drink again.", "二度と酒を飲まないと誓う"),
        ("Can discern the difference.", "違いを見分けることができる"),
        ("Degrade the environment.", "環境を悪化させる"),
        ("Erect barriers.", "障壁を築く"),
        ("Testify in court.", "法廷で証言する"),
        ("Spur him into action.", "彼を行動へと駆り立てる"),
        ("Roam the streets freely.", "通りを自由に歩き回る"),
        ("Frown on smoking.", "喫煙に眉をひそめる"),
        ("Lure tourists to Japan.", "観光客を日本に誘い込む"),
        ("Defy gravity.", "重力に逆らう"),
        ("Stroll in the park.", "公園を散歩する"),
        ("Rattle the windows.", "窓をガタガタ鳴らす"),
        ("Reconcile religion with science.", "宗教と科学を調和させる"),
        ("Blur the distinction.", "区別をあいまいにする"),
        ("Soothe the crying child.", "泣いている子どもをなだめる"),
        ("Impair learning ability.", "学習能力を損なう"),
        ("Comply with the standards.", "基準に従う"),
        ("Pierce my ears.", "耳にピアスの穴を開ける"),
        ("Stumble on the stairs.", "階段でつまずく"),
        ("Embody the spirit of the age.", "時代精神を体現する"),
        ("Stalk the prey.", "獲物にこっそり忍び寄る"),
        ("Proclaim that Japan is safe.", "日本は安全だと宣言する"),
        ("The audience applauds.", "観客が拍手する"),
        ("Inflict pain on other people.", "他人に苦痛を与える"),
        ("Merge with the company.", "その会社と合併する"),
        ("People were evacuated from the area.", "人々はその地域から避難した"),
        ("What is done cannot be undone.", "してしまったことは元に戻せない"),
        ("Poke him in the ribs.", "彼のわき腹をつつく"),
        ("Be haunted by memories of war.", "戦争の記憶に悩まされる"),
        ("Adhere to the international standards.", "国際基準を順守する"),
        ("Compile a list of customers.", "顧客リストを作成する"),
        ("The flowers will wither in the cold.", "花は寒さで枯れるだろう"),
        ("Stun the audience.", "観客をあ然とさせる"),
        ("Choke on a piece of food.", "食べ物をのどに詰まらせる"),
        ("His health will deteriorate.", "彼の健康は悪化するだろう"),
        ("Dump garbage in the street.", "通りにゴミを捨てる"),
        ("Murmur in a low voice.", "低い声でつぶやく"),
        ("Condemn his behavior.", "彼のふるまいを非難する"),
        ("Retrieve information.", "情報を取り出す"),
        ("Shrug your shoulders.", "肩をすくめる"),
        ("Evoke a response.", "反応を呼び起こす"),
        ("Fetch water from the river.", "川から水をくんでくる"),
        ("Flatter the boss.", "上司にお世辞を言う"),
        ("Write prose and poetry.", "散文と詩を書く"),
        ("The textile industry.", "繊維産業"),
        ("Cut timber.", "木材を切る"),
        ("Masterpieces of French art.", "フランス美術の傑作"),
        ("An anti-government riot.", "反政府暴動"),
        ("A train carriage.", "列車の客車"),
        ("Breathing apparatus.", "呼吸装置"),
        ("Make a fuss about nothing.", "何でもないことで大騒ぎする"),
        ("The heir to a fortune.", "財産の相続人"),
        ("A jungle at the equator.", "赤道直下のジャングル"),
        ("Import petroleum.", "石油を輸入する"),
        ("An evil witch.", "悪い魔女"),
        ("Water changes into vapor.", "水は蒸気に変わる"),
        ("A space probe.", "宇宙探査機"),
        ("Expertise in programming.", "プログラミングの専門知識"),
        ("A look of scorn.", "軽蔑のまなざし"),
        ("The prophets of the Bible.", "聖書の預言者たち"),
        ("A cool breeze from the sea.", "海からの涼しいそよ風"),
        ("Punishment for sin.", "罪に対する罰"),
        ("A surge in blood sugar.", "血糖値の急上昇"),
        ("A complement to medical treatment.", "医療を補完するもの"),
        ("Wait in a queue.", "列に並んで待つ"),
        ("A high-stakes poker game.", "大金を賭けたポーカー"),
        ("The French ambassador to Japan.", "駐日フランス大使"),
        ("The judge and jury.", "裁判官と陪審"),
        ("A cluster of neurons.", "神経細胞の集まり"),
        ("A lump on the head.", "頭のこぶ"),
        ("The green meadow.", "緑の牧草地"),
        ("Accomplish a remarkable feat.", "目覚ましい偉業を成し遂げる"),
        ("Artistic temperament.", "芸術家気質"),
        ("Feel a chill.", "寒気を感じる"),
        ("Electrical appliances.", "電化製品"),
        ("His predecessor as manager.", "部長としての彼の前任者"),
        ("A child is a separate entity.", "子どもは独立した存在だ"),
        ("Receive warm hospitality.", "温かいもてなしを受ける"),
        ("A narrative of his journey.", "彼の旅の物語"),
        ("A small segment of the population.", "人口の一部"),
        ("Prevent a catastrophe.", "大惨事を防ぐ"),
        ("The British monarch.", "イギリスの君主"),
        ("Due to time constraints.", "時間の制約のために"),
        ("An amendment to the law.", "法律の改正"),
        ("The structure of the cosmos.", "宇宙の構造"),
        ("Walk down the aisle.", "通路を歩く"),
        ("The top of the hierarchy.", "階層の頂点"),
        ("An expressway toll.", "高速道路の通行料金"),
        ("A transaction with the company.", "その会社との取引"),
        ("A burglar broke into the house.", "強盗がその家に押し入った"),
        ("Put up with tyranny.", "圧政に耐える"),
        ("An animal parasite.", "動物の寄生虫"),
        ("Women's intuition.", "女性の直感"),
        ("Former communist countries.", "旧共産主義国"),
        ("A legacy of the Renaissance.", "ルネサンスの遺産"),
        ("The veins in the forehead.", "額の静脈"),
        ("A discourse on politics.", "政治についての論説"),
        ("Dairy products.", "乳製品"),
        ("Asian art and artifacts.", "アジアの美術と工芸品"),
        ("An outlet for frustration.", "欲求不満のはけ口"),
        ("Watch with apprehension.", "不安な気持ちで見守る"),
        ("A mood of melancholy.", "憂うつな気分"),
        ("The quest for novelty.", "目新しさの追求"),
        ("A specimen of a rare plant.", "珍しい植物の標本"),
        ("Good hygiene practices.", "良い衛生習慣"),
        ("Use guerrilla tactics.", "ゲリラ戦術を使う"),
        ("A monopoly on the tea market.", "茶市場の独占"),
        ("As a token of our friendship.", "友情のしるしとして"),
        ("The English aristocracy.", "イギリスの貴族階級"),
        ("Take revenge on an enemy.", "敵に復讐する"),
        ("A human rights activist.", "人権活動家"),
        ("Empty rhetoric.", "空虚な美辞麗句"),
        ("A successful entrepreneur.", "成功した起業家"),
        ("Take a census every 10 years.", "10年ごとに国勢調査を行う"),
        ("Be on the verge of extinction.", "絶滅の危機に瀕している"),
        ("The advent of the internet.", "インターネットの出現"),
        ("An analogy between the heart and a pump.", "心臓とポンプの類似"),
        ("Irrigation systems.", "灌漑システム"),
        ("Media coverage of the accident.", "その事故の報道"),
        ("Traditional French cuisine.", "伝統的なフランス料理"),
        ("A menace to world peace.", "世界平和への脅威"),
        ("The perils of the road.", "道路の危険"),
        ("Have long limbs.", "手足が長い"),
        ("An assault on the enemy's base.", "敵の基地への攻撃"),
        ("Hatred of war.", "戦争への憎しみ"),
        ("Patient autonomy.", "患者の自己決定権"),
        ("Go to cram school.", "塾に通う"),
        ("A government subsidy.", "政府の補助金"),
        ("Empathy for others.", "他人への共感"),
        ("Slang expressions.", "俗語表現"),
        ("Maintain good posture.", "良い姿勢を保つ"),
        ("A political ideology.", "政治的イデオロギー"),
        ("Wealth can be a curse.", "富は災いのもとになりうる"),
        ("Have a brain tumor.", "脳腫瘍がある"),
        ("Turn right at the intersection.", "交差点で右に曲がる"),
        ("The duration of the contract.", "契約の期間"),
        ("Deforestation in the Amazon.", "アマゾンの森林破壊"),
        ("Take precautions against fires.", "火災への予防策を講じる"),
        ("A bunch of flowers.", "花束"),
        ("Put up with her shortcomings.", "彼女の欠点を我慢する"),
        ("Aspirations to be an artist.", "芸術家になりたいという熱望"),
        ("Psychologists and psychiatrists.", "心理学者と精神科医"),
        ("Packaging and shipping.", "梱包と発送"),
        ("A United States senator.", "アメリカの上院議員"),
        ("An international statesman.", "国際的な政治家"),
        ("Instruct a subordinate.", "部下に指示する"),
        ("Fill a vacuum.", "空白を埋める"),
        ("The quest for the truth.", "真理の探究"),
        ("Buddhist meditation.", "仏教の瞑想"),
        ("Subscribers to the service.", "そのサービスの加入者"),
        ("Solve a riddle.", "なぞなぞを解く"),
        ("Be dressed in rags.", "ぼろを着ている"),
        ("Be covered with rust.", "さびに覆われている"),
        ("Public sanitation.", "公衆衛生"),
        ("In the midst of the lecture.", "講義の最中に"),
        ("Childhood mischief.", "子ども時代のいたずら"),
        ("An English proficiency test.", "英語の能力試験"),
        ("Have no recollection of the past.", "過去の記憶がない"),
        ("38 degrees north latitude.", "北緯38度"),
        ("Friction between the two countries.", "両国間の摩擦"),
        ("Botanists study plants.", "植物学者は植物を研究する"),
        ("Contempt for authority.", "権威への軽蔑"),
        ("The anatomy of the human brain.", "人間の脳の構造"),
        ("A man of integrity.", "誠実な人"),
        ("A cargo ship.", "貨物船"),
        ("Take a bribe.", "賄賂を受け取る"),
        ("A massive volcanic eruption.", "大規模な火山の噴火"),
        ("Weddings and funerals.", "結婚式と葬式"),
        ("America's trade deficit.", "アメリカの貿易赤字"),
        ("The bulk of the population.", "人口の大部分"),
        ("How to marry a millionaire.", "百万長者と結婚する方法"),
        ("Be burned to ashes.", "焼けて灰になる"),
        ("Outside the realm of science.", "科学の領域の外"),
        ("Workers on banana plantations.", "バナナ農園の労働者"),
        ("A farmer with his plow.", "すきを持った農夫"),
        ("Buy a drink from a vending machine.", "自動販売機で飲み物を買う"),
        ("Look after orphans.", "孤児の世話をする"),
        ("Connections between neurons.", "神経細胞間のつながり"),
        ("Destroy the vegetation in the area.", "その地域の植生を破壊する"),
        ("A brave warrior.", "勇敢な戦士"),
        ("A genetic mutation.", "遺伝子の突然変異"),
        ("The city's sewage system.", "その都市の下水設備"),
        ("Propose a new paradigm.", "新しいパラダイムを提唱する"),
        ("The Kyoto Protocol.", "京都議定書"),
        ("Build a hundred-story skyscraper.", "100階建ての超高層ビルを建てる"),
        ("His opinion is in accord with mine.", "彼の意見は私と一致している"),
        ("Government bureaucrats.", "政府の官僚"),
        ("A vast array of spices.", "ずらりと並んだ香辛料"),
        ("A clash of civilizations.", "文明の衝突"),
        ("Endure terrible torture.", "ひどい拷問に耐える"),
        ("Queen Victoria's reign.", "ビクトリア女王の治世"),
        ("A graduation thesis.", "卒業論文"),
        ("A four-digit number.", "4桁の数字"),
        ("A political agenda.", "政治的課題"),
        ("The onset of dementia.", "認知症の発症"),
        ("Landless peasants in India.", "インドの土地を持たない小作農"),
        ("Harmful ultraviolet light.", "有害な紫外線"),
        ("A world-renowned singer.", "世界的に有名な歌手"),
        ("A transparent silk nightgown.", "透き通った絹の寝間着"),
        ("Read in dim light.", "薄暗い明かりで読書する"),
        ("A legitimate claim.", "正当な要求"),
        ("The adverse effect of global warming.", "地球温暖化の悪影響"),
        ("A swift reaction.", "すばやい反応"),
        ("Naive young people.", "世間知らずな若者たち"),
        ("I'm not as dumb as I look.", "私は見た目ほどばかではない"),
        ("Gloomy prospects.", "暗い見通し"),
        ("My father was furious with me.", "父は私に激怒していた"),
        ("Make an earnest effort.", "真剣な努力をする"),
        ("What a terrific idea!", "なんてすばらしい考えだ"),
        ("A vertical wall of rock.", "垂直な岩壁"),
        ("A wicked desire.", "邪悪な欲望"),
        ("A subjective impression.", "主観的な印象"),
        ("Enlightened young people.", "進んだ考えを持つ若者たち"),
        ("Authentic Italian food.", "本物のイタリア料理"),
        ("A brutal murder.", "残忍な殺人"),
        ("I feel dizzy when I stand up.", "立ち上がるとめまいがする"),
        ("Sheer good luck.", "まったくの幸運"),
        ("A naughty little boy.", "いたずらな小さい男の子"),
        ("Wipe with a damp towel.", "湿ったタオルで拭く"),
        ("Static electricity.", "静電気"),
        ("The plan is doomed to failure.", "その計画は失敗する運命にある"),
        ("Differ in innumerable ways.", "無数の点で異なる"),
        ("My clumsy fingers.", "私の不器用な指"),
        ("Aesthetic sensibility.", "美的感覚"),
        ("Be obsessed with dieting.", "ダイエットに取りつかれている"),
        ("A life detached from the world.", "世間から離れた生活"),
        ("A wrecked ship.", "難破した船"),
        ("His reckless driving.", "彼の無謀な運転"),
        ("His arrogant attitude.", "彼の傲慢な態度"),
        ("Be preoccupied with the problem.", "その問題で頭がいっぱいである"),
        ("A gigantic spaceship.", "巨大な宇宙船"),
        ("The most conspicuous example.", "最も目立つ例"),
        ("A slender girl with long hair.", "長い髪のほっそりした少女"),
        ("A manifest mistake.", "明白な間違い"),
        ("Keep the room tidy.", "部屋をきちんとしておく"),
        ("A skeptical view of life.", "人生への懐疑的な見方"),
        ("A notorious crime.", "悪名高い犯罪"),
        ("An anonymous letter.", "匿名の手紙"),
        ("A monotonous school life.", "単調な学校生活"),
        ("Have ample opportunity to learn.", "学ぶ機会が十分にある"),
        ("A trim appearance.", "こぎれいな身なり"),
        ("Savage violence.", "残忍な暴力"),
        ("A logically coherent system.", "論理的に首尾一貫した体系"),
        ("An eloquent speech.", "雄弁な演説"),
        ("A foul-smelling gas.", "悪臭のするガス"),
        ("A rise in juvenile crime.", "少年犯罪の増加"),
        ("Compulsory education.", "義務教育"),
        ("Be prone to catch fire.", "火がつきやすい"),
        ("An arbitrary decision.", "恣意的な決定"),
        ("An ingenious design.", "独創的な設計"),
        ("The divine right of kings.", "王権神授説"),
        ("A tender smile.", "優しいほほえみ"),
        ("Be outraged by his behavior.", "彼のふるまいに激怒する"),
        ("The intrinsic value of gold.", "金の本質的価値"),
        ("Be paralyzed from the waist down.", "腰から下がまひしている"),
        ("Be compatible with their values.", "彼らの価値観と両立する"),
        ("Shout patriotic slogans.", "愛国的なスローガンを叫ぶ"),
        ("An eminent scientist.", "著名な科学者"),
        ("A potent weapon.", "強力な武器"),
        ("Be completely insane.", "完全に正気を失っている"),
        ("A staple food.", "主食"),
        ("Secondhand smoke.", "受動喫煙の煙"),
        ("Indigenous peoples of Australia.", "オーストラリアの先住民"),
        ("Be of the utmost importance.", "最も重要である"),
        ("An integral part of society.", "社会に不可欠な部分"),
        ("An intricate pattern.", "複雑な模様"),
        ("Demographic changes.", "人口構成の変化"),
        ("A mighty king.", "強大な王"),
        ("The building remains intact.", "その建物は無傷のまま残っている"),
        ("Be intent on marrying him.", "彼と結婚しようと固く決心している"),
        ("A very intriguing question.", "とても興味をそそる問題"),
        ("Perpetual peace.", "永遠の平和"),
        ("A spinal injury.", "脊椎の負傷"),
        ("Be susceptible to disease.", "病気にかかりやすい"),
        ("Mandatory standards for safety.", "安全のための強制基準"),
        ("Stand upright.", "まっすぐに立つ"),
        ("Stop abruptly.", "突然止まる"),
        ("Predominantly female jobs.", "主に女性が就く仕事"),
        ("He wrote it down lest he forget.", "忘れないように彼はそれを書き留めた"),
    ]

    static func seedIfNeeded(context: ModelContext) {
        let key = "didSeedVocab_v1"
        guard !entries.isEmpty, !UserDefaults.standard.bool(forKey: key) else { return }

        let descriptor = FetchDescriptor<VocabWord>()
        let existing = Set((try? context.fetch(descriptor))?.map(\.english) ?? [])
        for (index, pair) in entries.enumerated() where !existing.contains(pair.0) {
            context.insert(VocabWord(index: index, english: pair.0, japanese: pair.1))
        }
        try? context.save()
        UserDefaults.standard.set(true, forKey: key)
    }
}
